{
  imports = [
    ./fonts
    ./boot.nix 
    ./environment.nix 
    ./locale.nix 
    ./hardware.nix
    ./services.nix
    ./sound.nix
    ./utils.nix
    ./xdg.nix
    ./network.nix
    ./zram.nix
    ./security.nix
    ./intel.nix
    ./power.nix
    ./keyring.nix
    ./sddm.nix
    ./shell.nix
  ];
}
